name: "PR Review Apps on fly.io"
description: "Deploy temporary apps from pull requests on Fly.io"
author: Fly
branding:
  icon: "upload-cloud"
  color: "purple"
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  name:
    description: Fly app name
  region:
    description: Region to launch the app in (alternatively, set the env FLY_REGION)
  org:
    description: Organization to launch the app in (alternatively, set the env FLY_ORG)
  path:
    description: path to a directory containing a fly.toml to clone
  postgres:
    description: Optionally attach the app to a pre-existing Postgres cluster on Fly
  dockerfile:
    description: Path to a Dockerfile, will be used for building the image
    required: true
