name: "PR Review Apps on fly.io"
description: "Deploy temporary apps from pull requests on Fly.io"
author: Fly
branding:
  icon: "upload-cloud"
  color: "purple"
runs:
  using: "docker"
  image: "Dockerfile"
inputs:
  name:
    description: Fly app name
  image:
    description: Optional pre-existing Docker image to use
  config:
    description: Optional path to a custom Fly toml config. Config path should be relative to `path` parameter, if specified.
  region:
    description: Region to launch the app in (alternatively, set the env FLY_REGION)
  org:
    description: Organization to launch the app in (alternatively, set the env FLY_ORG)
  path:
    description: path to a directory containing a fly.toml to clone
  postgres:
    description: Optionally attach the app to a pre-existing Postgres cluster on Fly
  update:
    description: Whether new commits to the PR should re-deploy the Fly app
    default: true
  secrets:
    description: Secrets to be set on the app. Separate multiple secrets with a space
  vm:
    description: Set app VM to a named size, eg. shared-cpu-1x, dedicated-cpu-1x, dedicated-cpu-2x etc. (defaults to shared-cpu-1x)
  memory:
    description: Set app VM memory (defaults to 256 megabytes)
  count:
    description: Set app VM count to the given value (defaults to 1)
